### ISSUE TITLE
Centre de gestion : !informations gestionnaires

### ISSUE THREAD

**Issue by ribetb** [EsupPortail/esup-stage#137]
Bonjour,

Rattacher un gestionnaire

Lorsque l’on clique sur une personne rattachée au centre, les informations ne sont pas à jour.

![image](https://github.com/EsupPortail/esup-stage/assets/106594886/ff3e4716-64c5-46ea-9bdf-f6b583278367)

L'appli esup-stage pointe vers le supann sur la base dc=uga,dc=fr
Dans le supann sont bien présents les n° de téléphone : telephoneNumber et l'adresse : postalAddress (attention au format de ce champ - ex. : FORM-DOIP$bureau Bureau 121 - 1er étage$PMF$CAMPUS)

Comment sont remontées les informations lorsqu'on veut rattacher un gestionnaire à un centre de gestion ?

Voici le fichier les champs du fichier de conf application.yml

```
attributes:
      objectClass: Person
      supannAliasLogin: uid
      baseDn: ou=people
      dn: dn
      uid: uid
      codEtu: supannEtuId
      supannEtuId: supannEtuId
      sn: sn
      mail: mail
      supannAutreMail: supannAutreMail
      cn: cn
      givenName: givenName
      displayName: givenName
      eduPersonPrimaryAffiliation: eduPersonPrimaryAffiliation
      eduPersonAffiliation: eduPersonAffiliation
      supannEntiteAffectation: supannEntiteAffectation
      supannEntiteAffectationPrincipale: supannEntiteAffectationPrincipale
      supannCivilite: supannCivilite
      telephoneNumber: telephoneNumber
      supannEtuCursusAnnee: supannEtuCursusAnnee
     # eduPersonOrgDN: eduPersonOrgDN
      eduPersonOrgDN: eduOrgLegalName
      supannEmpId: supannEmpId
      supannRefId: supannRefId
      supannEtuEtape: supannEtuEtape
      supannEtuAnneeInscription: supannEtuAnneeInscription
      etudiantLogin: uid
      uidEnseignant: uid
```

Nous recevons le nom, le prénom et le mail qui remontent. Le reste ne remonte pas : téléphone, affectation, bâtiment, campus et bureau. L'affectation et le téléphone devraient au moins remonter car présents dans le fichier de conf ci dessus. Pour les autres champs, pouvez vous nous indiquer les champs à paramétrer ?

Bonne journée
Beatrice Ribet (rd 552)
